# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shortcut.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShortcutDlg(object):
    def setupUi(self, ShortcutDlg):
        ShortcutDlg.setObjectName("ShortcutDlg")
        ShortcutDlg.resize(401, 544)
        ShortcutDlg.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.formLayoutWidget = QtWidgets.QWidget(ShortcutDlg)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 511))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_10)

        self.retranslateUi(ShortcutDlg)
        QtCore.QMetaObject.connectSlotsByName(ShortcutDlg)

    def retranslateUi(self, ShortcutDlg):
        _translate = QtCore.QCoreApplication.translate
        ShortcutDlg.setWindowTitle(_translate("ShortcutDlg", "Shortcut"))
        self.label.setText(_translate("ShortcutDlg", "CTRL + S"))
        self.label_2.setText(_translate("ShortcutDlg", "Lựu lại thông tin toàn bộ khu vực đã apply"))
        self.label_3.setText(_translate("ShortcutDlg", "CTRL + D"))
        self.label_5.setText(_translate("ShortcutDlg", "Apply thông tin khu vực"))
        self.label_4.setText(_translate("ShortcutDlg", "Q"))
        self.label_6.setText(_translate("ShortcutDlg", "Chọn tool vẽ khu vực"))
        self.label_7.setText(_translate("ShortcutDlg", "Delete"))
        self.label_8.setText(_translate("ShortcutDlg", "Xóa khu vực được chọn"))
        self.label_9.setText(_translate("ShortcutDlg", "CTRL + O"))
        self.label_10.setText(_translate("ShortcutDlg", "Mở ảnh "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShortcutDlg = QtWidgets.QWidget()
    ui = Ui_ShortcutDlg()
    ui.setupUi(ShortcutDlg)
    ShortcutDlg.show()
    sys.exit(app.exec_())
